
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato-deployment
  labels:
    env: green
spec:
  replicas: 10

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 3

  selector:
    matchLabels:
      app: zomato
      env: green
  template:
    metadata:
      labels:
        app: zomato
        env: green
    spec:
      containers:
        - name: container-1
          image: vishalgogula123/devops:bus
          ports:
            - containerPort: 80
