
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-deployment
  labels:
    env: green
spec:
  replicas: 10

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 3

  selector:
    matchLabels:
      app: swiggy
      env: green
  template:
    metadata:
      labels:
        app: swiggy
        env: green
    spec:
      containers:
        - name: container-1
          image: vishalgogula123/devops:bus
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: swiggy-config
            - secretRef:
                name: swiggy-secret
