---
apiVersion: v1
kind: Secret
metadata:
  name: swiggy-secret
data:
  username: V2hpdGVTbmFrZTEyMw==  # base64 encoded value of "swiggyuser"
  password: QmxhY2tTbmFrZTEyMw== # base64 encoded value of "swiggypassword"
